disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - discarded_notification_center_observer
  - type_body_length
  - nesting
  - large_tuple
  - function_parameter_count
  - trailing_whitespace
  - void_return
  - closure_end_indentation
  - file_header
  - inclusive_language
  
opt_in_rules:
  - force_unwrapping
  - closure_end_indentation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  
excluded:
  - Pods
  - DarknessBot/Models/Common/Localizables.swift
  - DarknessBot/External/Charts

line_length:
  warning: 120
  error: 120
  ignores_urls: true
  ignores_comments: true
  
file_length:
  warning: 1000
  error: 2000
  
identifier_name:
  min_length: 1
  max_length: 60

type_name:
  min_length: 3
  max_length: 60

#Будет ошибка при принудительном касте типов
force_cast:
  error
  
#Ошибка при точке с запятой на конце
trailing_semicolon:
  error
  
#Будет ошибка при излишних скобках
control_statement:
  error

#Будет ошибка при лишнем указании getter-a
implicit_getter:
  error

#Будет ошибка, если параметры метода расположены вертикально и не из одной табуляции
vertical_parameter_alignment:
  error

#Будет ошибка при отсутствии нужных пробелов при указании возвращаемого значения
return_arrow_whitespace:
  error

#Будет ошибка при лишнем упоминании неиспользуемых объектов
unused_optional_binding:
  error

#Будет ошибка при указании уточненных типов массивов и словарей в устаревших форматах
syntactic_sugar:
  error

#Кастомные правила
custom_rules:
  dp_void_return:
    name: "Неверное использование Void"
    regex: "([(](Void)?[)] ?-> ?Void)"
    match_kinds:
      - typeidentifier
    message: "Используй '() -> ()'"
    severity: error
    
  dp_guard_self:
    name: "Неверное использование guard let self = self"
    regex: "guard\\s+let\\s+(((?!self).)\\S* = self[ ,]|`self` = self)"
    message: "Используй 'guard let self = self'"
    severity: error
    
#   dp_types_String:
#     name: "Лишнее указание типа"
#     regex: "(var|let) \\w*: String = \""
#     message: "Не указывай тип"
#     severity: error
    
  dp_types_Int:
    name: "Лишнее указание типа"
    regex: "(var|let) \\w*: Int = \\d"
    message: "Не указывай тип"
    severity: error
    
#   dp_types_Bool:
#     name: "Лишнее указание типа"
#     regex: "(var|let) \\w*: Bool = (true|false)"
#     message: "Не указывай тип"
#     severity: error
    
  dp_types_Double:
    name: "Лишнее указание типа"
    regex: "(var|let) \\w*: Double = \\d"
    message: "Не указывай тип"
    severity: error 
    
  dp_types_Date:
    name: "Лишнее указание типа"
    regex: "(var|let) \\w*: Date = Date\\("
    message: "Не указывай тип"
    severity: error

  custom_cyrillic_file_name:
    name: "Использование кириллицы в названии файлов запрещено"
    regex: "[A-Za-z]*[ЁёА-я]+[A-Za-z]*(\\.swift)$"
    message: "Проверь имя файла на наличие символов кириллицы"
    match_kinds:
      - comment
    severity: error

  custom_cyrillic_code:
    name: "Использование кириллицы вне комментариев, строк и документации запрещено"
    regex: "[ЁёА-я]"
    message: "Проверь название на содержание символов кириллицы"
    match_kinds:
      - argument
      - identifier
      - keyword
      - parameter
      - typeidentifier
    severity: error 

# warning_threshold: 100

custom_func_line_breaks:
  name: "Переносы при вызове функции"
  regex: "\\w+\\((\\w+: |)[\\w.|\\[\\]\":$%]+,$"
  message: "Переносы строк необходимо делать по гайду"
  severity: error